// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zWATsD4PUHeFRaS4mj-Dg_hlnvUEHe8',
    appId: '1:217850894385:web:03595ebdd3eaeb13c21d10',
    messagingSenderId: '217850894385',
    projectId: 'istoreappflutter',
    authDomain: 'istoreappflutter.firebaseapp.com',
    storageBucket: 'istoreappflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzJWz52sR4RTNAGwApCyWAT6fkLoUMnFc',
    appId: '1:217850894385:android:31bd504fc2b3b62dc21d10',
    messagingSenderId: '217850894385',
    projectId: 'istoreappflutter',
    storageBucket: 'istoreappflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYd_XbPxjO3t-n7GNDHOX8KNPvsUh_sWE',
    appId: '1:217850894385:ios:ec2ba46f818905e4c21d10',
    messagingSenderId: '217850894385',
    projectId: 'istoreappflutter',
    storageBucket: 'istoreappflutter.appspot.com',
    iosClientId: '217850894385-371lgn5rlopjfmdrbrvqh08tnk3d73cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.iStore',
  );
}
